# Generated by Django 5.2.5 on 2025-10-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportDate', models.TextField(default=0)),
                ('reportTime', models.TextField(default=0)),
                ('result_string', models.TextField(default='')),
                ('reportHash', models.TextField(default=0)),
                ('reportSignature', models.TextField(default=0)),
                ('reportJsonbody', models.TextField(default=0)),
                ('fiscalDayStatus', models.TextField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalBranch',
            fields=[
                ('branch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pos.branch')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('production', models.BooleanField(default=False)),
                ('keystore', models.FileField(blank=True, null=True, upload_to='FILES/certificates/')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('private_key', models.FileField(blank=True, null=True, upload_to='FILES/certificates/')),
                ('public_key', models.FileField(blank=True, null=True, upload_to='FILES/certificates/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='FILES/certificates/')),
                ('globalNo', models.IntegerField(default=1)),
                ('base_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fiscal Branch',
                'verbose_name_plural': 'Fiscal Branches',
            },
            bases=('pos.branch',),
        ),
        migrations.CreateModel(
            name='ReceiptError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('severity', models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow')], max_length=10)),
                ('blocks_submission', models.BooleanField(default=False)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Receipt Error',
                'verbose_name_plural': 'Receipt Errors',
            },
        ),
        migrations.CreateModel(
            name='FiscalReportEntry',
            fields=[
                ('reportentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pos.reportentry')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fiscalization.dailyreports')),
            ],
            bases=('pos.reportentry',),
        ),
        migrations.CreateModel(
            name='OpenDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FiscalDayNo', models.IntegerField(null=True)),
                ('FiscalDayOpened', models.TextField(null=True)),
                ('FiscalDayClosed', models.TextField(null=True)),
                ('counter', models.IntegerField(default=1)),
                ('open', models.BooleanField(default=1)),
                ('no_of_receipts_usd', models.IntegerField(default=0)),
                ('no_of_credits_zwl', models.IntegerField(default=0)),
                ('no_of_receipts_zwl', models.IntegerField(default=0)),
                ('no_of_credits_usd', models.IntegerField(default=0)),
                ('previousReceiptHash', models.TextField(default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalization.fiscalbranch')),
            ],
        ),
        migrations.AddField(
            model_name='dailyreports',
            name='FiscalDay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscalization.openday'),
        ),
        migrations.CreateModel(
            name='ReceiptCounters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('type', models.TextField(default='')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.currency')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscalization.openday')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalReceipt',
            fields=[
                ('receipt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pos.receipt')),
                ('qrurl', models.TextField(null=True)),
                ('receiptJsonbody', models.TextField(null=True)),
                ('receiptHash', models.TextField(null=True)),
                ('signature', models.TextField(null=True)),
                ('submited', models.BooleanField(default=False)),
                ('serverResponse', models.TextField(null=True)),
                ('md5_hash', models.TextField(null=True)),
                ('receiptGlobalNo', models.IntegerField(default=1)),
                ('receiptCounter', models.IntegerField(default=1)),
                ('result_string', models.TextField(default='')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(null=True)),
                ('fiscal_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscalization.fiscalbranch')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiscalization.openday')),
                ('errors', models.ManyToManyField(blank=True, to='fiscalization.receipterror')),
            ],
            bases=('pos.receipt',),
        ),
        migrations.CreateModel(
            name='FiscalCredit',
            fields=[
                ('fiscalreceipt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fiscalization.fiscalreceipt')),
                ('reason', models.TextField(null=True)),
                ('fiscal_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_credit', to='fiscalization.fiscalreceipt')),
            ],
            bases=('fiscalization.fiscalreceipt',),
        ),
        migrations.CreateModel(
            name='FiscalDebit',
            fields=[
                ('fiscalreceipt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fiscalization.fiscalreceipt')),
                ('reason', models.TextField(null=True)),
                ('fiscal_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_debit', to='fiscalization.fiscalreceipt')),
            ],
            bases=('fiscalization.fiscalreceipt',),
        ),
    ]
