# Generated by Django 5.2.5 on 2025-10-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fiscalization.openday'),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='receiptCounter',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='receiptGlobalNo',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='result_string',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='submited',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
