# Generated by Django 5.2.5 on 2025-10-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalization', '0002_alter_fiscalreceipt_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalreceipt',
            name='qrcode',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
