# Generated by Django 5.2.5 on 2025-10-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalization', '0003_fiscalreceipt_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalreceipt',
            name='qrcode',
            field=models.FileField(null=True, upload_to='C:\\Users\\Kudzai\\Desktop\\PressPOS3.0\\FILES/html'),
        ),
    ]
