# Generated by Django 5.2.5 on 2025-10-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalization', '0004_alter_fiscalreceipt_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openday',
            name='no_of_credits_usd',
        ),
        migrations.RemoveField(
            model_name='openday',
            name='no_of_credits_zwl',
        ),
        migrations.RemoveField(
            model_name='openday',
            name='no_of_receipts_usd',
        ),
        migrations.RemoveField(
            model_name='openday',
            name='no_of_receipts_zwl',
        ),
    ]
