# Generated by Django 5.2.5 on 2025-10-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscalization', '0005_remove_openday_no_of_credits_usd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiscalreceipt',
            old_name='day',
            new_name='fiscal_day',
        ),
    ]
