# Generated by Django 5.2.5 on 2025-10-23 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_rename_total_price_receiptitem_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='invoiceItems',
        ),
    ]
