# Generated by Django 5.2.5 on 2025-10-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_transaction_invoiceitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taxExclusive',
            field=models.DecimalField(decimal_places=5, default=0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(decimal_places=5, default=0, editable=False, max_digits=10, null=True),
        ),
    ]
