# Generated by Django 5.2.5 on 2025-10-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_transaction_created_at_transaction_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='taxExclusive',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat',
        ),
    ]
