# Generated by Django 5.2.5 on 2025-10-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_product_taxexclusive_remove_product_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
    ]
